name: value_container
description: This package will help you separate values and validate them each one on its own
version: 1.0.0
repository: https://github.com/Davenchy/value_container

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
